stages:
- start
- process
- exit

batch_job:1:
  stage: start
  script:
    #- python extract_and_decide.py
    - echo "Run batch_job:1"
  #artifacts:
  #  paths:
  #    - output/

batch_job:2:
  stage: start
  script:
    #- python extract_and_decide.py
    - echo "Run batch_job:2"
  #artifacts:
  #  paths:
  #    - output/

batch_job:3:
  stage: start
  script:
    #- python extract_and_decide.py
    - echo "Run batch_job:3"
  #artifacts:
  #  paths:
  #    - output/

noop:
  stage: process
  script: []

batch_job:goto:
  stage: exit
  needs:
  - noop
  script:
  - curl -X POST -F token=${TRIGGER_TOKEN} -F ref=${CI_COMMIT_REF_NAME} -F "variables[TEMPLATE_FILE_NAME_URL]=https://raw.githubusercontent.com/sergeimonakhov/test-pipeline/refs/heads/main/batch_job_1.yml" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
